- name: installing backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed
  - name: creating user 
    ansible.builtin.user:
      name: expense
  - name: creating a directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the source code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: extracting the code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
     