- name: installing mysql
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: "ExpenseApp@1"
    mysql_host_address: "mysql.manohar.fun"
  tasks:
  - name: installing PyMySQL
    ansible.builtin.package:
      name: PyMySQL
      state: installed
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: starting mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: setting up root password
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ mysql_host_address }}"
  

